steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/october-now-restaurant-portal", "--build-arg", "configuration='$_CONFIG'", "."]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/october-now-restaurant-portal"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["beta","run","deploy","--allow-unauthenticated","on-restaurant-portal","--image","gcr.io/$PROJECT_ID/october-now-restaurant-portal","--region","europe-west1","--platform","managed","--memory","128Mi"]
images:
  - gcr.io/$PROJECT_ID/october-now-restaurant-portal
timeout: 2400s
